# Generated by Django 2.2.1 on 2019-05-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especificacionproducto',
            unique_together={('esp_item', 'esp_producto')},
        ),
    ]
