# Generated by Django 2.2.1 on 2019-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cat_nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
    ]
