# Generated by Django 2.2.1 on 2019-06-21 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20190521_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
